domainMappings:
#  北美
  - domainSuffix: ".com"
    region: "us-east-1"
    countryCode: "US"
    chineseName: "美国"
  - domainSuffix: ".ca"
    region: "us-east-1"
    countryCode: "CA"
    chineseName: "加拿大"
  - domainSuffix: ".com.mx"
    region: "us-east-1"
    countryCode: "MX"
    chineseName: "墨西哥"
  - domainSuffix: ".com.br"
    region: "us-east-1"
    countryCode: "BR"
    chineseName: "巴西"
#    欧洲
  - domainSuffix: ".es"
    region: "eu-west-1"
    countryCode: "ES"
    chineseName: "西班牙"
  - domainSuffix: ".co.uk"
    region: "eu-west-1"
    countryCode: "UK"
    chineseName: "英国"
  - domainSuffix: ".fr"
    region: "eu-west-1"
    countryCode: "FR"
    chineseName: "法国"
  - domainSuffix: ".com.be"
    region: "eu-west-1"
    countryCode: "BE"
    chineseName: "比利时"
  - domainSuffix: ".nl"
    region: "eu-west-1"
    countryCode: "NL"
    chineseName: "荷兰"
  - domainSuffix: ".de"
    region: "eu-west-1"
    countryCode: "DE"
    chineseName: "德国"
  - domainSuffix: ".it"
    region: "eu-west-1"
    countryCode: "IT"
    chineseName: "意大利"
  - domainSuffix: ".se"
    region: "eu-west-1"
    countryCode: "SE"
    chineseName: "瑞典"
  - domainSuffix: ".eg"
    region: "eu-west-1"
    countryCode: "EG"
    chineseName: "埃及"
  - domainSuffix: ".com.tr"
    region: "eu-west-1"
    countryCode: "TR"
    chineseName: "土耳其"
  - domainSuffix: ".sa"
    region: "eu-west-1"
    countryCode: "SA"
    chineseName: "沙特阿拉伯"
  - domainSuffix: ".ae"
    region: "eu-west-1"
    countryCode: "AE"
    chineseName: "阿拉伯联合酋长国"
  - domainSuffix: ".in"
    region: "eu-west-1"
    countryCode: "IN"
    chineseName: "印度"
# 远东
  - domainSuffix: ".com.au"
    region: "us-west-2"
    countryCode: "AU"
    chineseName: "澳大利亚"
  - domainSuffix: ".co.jp"
    region: "us-west-2"
    countryCode: "JP"
    chineseName: "日本"
  - domainSuffix: ".sg"
    region: "us-west-2"
    countryCode: "SG"
    chineseName: "新加坡"